=== AndriiDiachuk/Dragger/ConsoleUI/bin/Debug/levels/SokobanLev.dtd
<!-- ================== SokobanLevels ====================================== -->
<!ELEMENT SokobanLevels (Title, LevelCollection)>

<!ELEMENT Title (#PCDATA)>


<!ELEMENT LevelCollection (Level+)>
<!ATTLIST LevelCollection
                Copyright CDATA ""
                MaxWidth     CDATA #IMPLIED
                MaxHeight    CDATA #IMPLIED>

<!ELEMENT Level (L+)>
<!ATTLIST Level Id        CDATA #REQUIRED
                Width     CDATA #IMPLIED
                Height    CDATA #IMPLIED
                Copyright CDATA "">

<!ELEMENT L (#PCDATA)>
<!ATTLIST L xml:space (default|preserve) 'preserve'>

<!-- ======================================================================= -->

=== AndriiDiachuk/Dragger/ConsoleUI/bin/Debug/levels/boxworld.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE SokobanLevels SYSTEM "SokobanLev.dtd">
<SokobanLevels>
  <Title>Levels 1-2</Title>
  <Description>The levels from the Drager game</Description>
  <LevelCollection MaxWidth="13" MaxHeight="11">
    <Level Id="BW1" Width="9" Height="9">
      <L>#####</L>
      <L>#@  #</L>
      <L># $$#=###</L>
      <L># $ #=#.#</L>
      <L>### ###.#</L>
      <L> ##    .#</L>
      <L> #   #  #</L>
      <L> #   ####</L>
      <L> #####</L>
    </Level>
  </LevelCollection>
</SokobanLevels>
